name: Update Blog Posts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  update_blog:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run Update Python Script
      run: python main.py

    - name: Update README.md file
      run: | 
        git add .
        git diff
        git config --local user.email "gamin3182@gmail.com"
        git config --local user.name "22gamin"
        git commit -m "Updating Blog Posts"
        git push
